### ISSUE TITLE
Actions in different languages possible?

### ISSUE THREAD

**Issue by noestreich** [andersrex/notesollama#2]
Great Notes Plugin, but it seems to only replay (or use the inbuild actions) in english. 

I already tried to create a llama2-instance with a systemprompt to always reply in german, but used via notesollama, the summarizing is only done in english, even if the input-text is german (and with the altered system-prompt).

**Comment by andersrex** [comment]
I pushed a quick workaround where you can edit the commands in JSON and then restart NotesOllama ([commit](https://github.com/andersrex/notesollama/commit/77fa505a9317604d042d7904bbe63e07f4bd0e99)):

`$ vim NotesOllama.app/Contents/Resources/commands.json`
