### ISSUE TITLE
vision task failed

### ISSUE THREAD

**Issue by jerlinn** [andersrex/notesollama#5]
I set llava as the model, noticed that the image parameters don't seem to have been passed to the model, it keeps giving irrelevant answers.
![CleanShot 2024-03-09 at 22 08 41@2x](https://github.com/andersrex/notesollama/assets/91647085/616b3e68-4f89-4612-93dd-059ddd0b5011)

Try a prompt way, nothing changed.
    {
      "name": "Caption image",
      "prompt": "Act as a image captioner. Create only one single heading for the selected image that gives a good understanding of what the reader can expect. Output only the caption and nothing else (such as symbols), do not chat, no preamble, get to the point. Your format should be ## Caption."
    }

**Comment by jerlinn** [comment]
maybe here?
![CleanShot 2024-03-09 at 22 24 14@2x](https://github.com/andersrex/notesollama/assets/91647085/f88cab91-6b08-475f-9078-5ceace689d37)

**Comment by andersrex** [comment]
Thanks for reporting this. I looked into it a bit and to support vision models we'd need to figure out a file path for the image. 

The selectedText here only returns selected text, it drops any images in the selection: https://github.com/andersrex/notesollama/blob/main/NotesOllama/NotesWatcher.swift#L44

I haven't found a way to access image data using the accessibility API:
<img width="868" alt="Screenshot 2024-03-11 at 10 36 26" src="https://github.com/andersrex/notesollama/assets/1891619/e698dbf1-a1cb-491a-87e1-5d5cec6fd0ba">
