### ISSUE TITLE
Using customed ollama server

### ISSUE THREAD

**Issue by sheldon123z** [andersrex/notesollama#7]
Hi, 
This is a beautiful plugin, but I don't use Ollama on my Mac since the models are too big. So, my question is, how can we change the alloma proxy URL?

**Comment by andersrex** [comment]
Does it work if you change it here?

https://github.com/andersrex/notesollama/blob/main/NotesOllama/Services/OllamaService.swift#L12

**Comment by rb81** [comment]
+1 - Being able to change the Ollama server endpoint would be great. There are many use cases for this, one is allowing applications running in Docker to access Ollama running on the local machine (which is what I'm doing). I don't want to start routing stuff, so this feature would be great.

**Comment by cori** [comment]
I run Ollama on a "NUC" with a GPU that's available over my local network so I'd love this as well.

**Comment by soham2008xyz** [comment]
@andersrex Since the NotesOllama app doesn't come with any UI at the moment, should this be made configurable using an environment variable? (e.g. `NOTESOLLAMA_OLLAMA_BASE_URL`)

If this works, I can draft a pull request for this change.

**Comment by rb81** [comment]
> @andersrex Since the NotesOllama app doesn't come with any UI at the moment, should this be made configurable using an environment variable? (e.g. `NOTESOLLAMA_OLLAMA_BASE_URL`)
> 
> If this works, I can draft a pull request for this change.

This would be great!

**Comment by andersrex** [comment]
Merged, thanks for making the PR! I'll get a new release out ASAP
